name: Generate E2E Test Automatic Report

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17   MON" # every monday at 17

jobs:
  test:
    timeout-minutes: 355
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Setup chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 127
        

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Test ignoring failures
        run: mvn clean test -Dheadless=true
        continue-on-error: true
      - name: Save Cucumber test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target

  cucumber-report:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get repository history
        uses: actions/checkout@v3
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Get test results
        uses: actions/download-artifact@v2
        with:
          name: test-results
          path: target

      - name: Rename cucumber.html to index.html
        run: mv target/cucumber.html target/index.html

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./target
